### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by zibass** [umehara-lp/Simple-Sftp-Upload#5]
After installing the extension this sends error and does not show any menu to configure or use it
![captura](https://user-images.githubusercontent.com/1046248/28593331-f5ad59cc-7159-11e7-9244-0bc8a52447f1.JPG)

Extension version 1.4.7
Brackets 1.10.0.-17483

**Comment by umehara-lp** [comment]
Excuse me.
We responded so that no error occurs in languages other than English.
Please try using it.

**Comment by magicbruno** [comment]
I found that in my enviroments (Windows 10, language it) app init fails when tries to add a new item to main menu. This happens because the STRINGS variable that should contain app localized strings is an empty object. I found this solution.
I created a root entry in au.brackets-simple-sftp-upload\nls\Strings.js:
```
define( function( require, exports, module ) {
	'use strict';	
	module.exports = {
		root: true,
		en: true,
		ja: true
	};
} );
```
and a corresponding Strings.js file in au.brackets-simple-sftp-upload\nls\root copying content of au.brackets-simple-sftp-upload\nls\en\Strings.js. 
Now the extension loads as expected and new menu item is created correctly..
